In [1]:
import numpy as np 
import torch

### Creating 1D, 2D, and 3D Tensors

In [ ]:
# 1D
a_1d = np.array([1, 2, 3])
# 2D
a_2d = np.array([[1, 2],
                 [3, 4]])
# 3D
a_3d = np.array([[[1, 2], [3, 4]],
                 [[5, 6], [7, 8]]])

In [4]:
import torch


t_1d = torch.tensor([1, 2, 3])


t_2d = torch.tensor([[1, 2],
                     [3, 4]])

t_3d = torch.tensor([[[1, 2], [3, 4]],
                     [[5, 6], [7, 8]]])


### Basic Element-wise Operations

In [7]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

print(a + b)
print(a - b)
print(a * b)
print(a / b)



[5 7 9]
[-3 -3 -3]
[ 4 10 18]
[0.25 0.4  0.5 ]


In [9]:
x = torch.tensor([1, 2, 3])
y = torch.tensor([4, 5, 6])

print(x + y)
print(x - y)
print(x * y)
print(x / y)



tensor([5, 7, 9])
tensor([-3, -3, -3])
tensor([ 4, 10, 18])
tensor([0.2500, 0.4000, 0.5000])


### Dot Product & Matrix Multiplication


In [12]:
print(np.dot(a, b))



32


In [13]:
print(torch.dot(x, y))


tensor(32)


### Matrix Multiplication (2D)

In [14]:
A = np.array([[1, 2],
              [3, 4]])
B = np.array([[5, 6],
              [7, 8]])

print(A @ B)




[[19 22]
 [43 50]]


In [15]:
A = torch.tensor([[1, 2],
                  [3, 4]])
B = torch.tensor([[5, 6],
                  [7, 8]])

print(A @ B)


print(torch.matmul(A, B))


tensor([[19, 22],
        [43, 50]])
tensor([[19, 22],
        [43, 50]])


### Indexing & Slicing

In [17]:
x = torch.tensor([[10, 20, 30],
                  [40, 50, 60]])

print(x[0, 1])    
print(x[:, 1] )   
print(x[1, :]  )   


tensor(20)
tensor([20, 50])
tensor([40, 50, 60])


In [18]:
a = torch.tensor([1, 2, 3, 4, 5])

mask = a > 3
print(a[mask] )    


tensor([4, 5])


In [ ]:
t = torch.tensor([[1, 2, 3],
                  [4, 5, 6],
                  [7, 8, 9]])

print(t[:2, :2] )



tensor([[1, 2],
        [4, 5]])


### Shape Manipulation

In [23]:
x = torch.tensor([1, 2, 3, 4])

print(x.view(2, 2))


tensor([[1, 2],
        [3, 4]])


In [24]:
x.reshape(2, 2)


tensor([[1, 2],
        [3, 4]])

In [26]:
a = np.array([1, 2, 3, 4])
a.reshape(2, 2)


array([[1, 2],
       [3, 4]])

In [ ]:
x = torch.tensor([1, 2, 3])

x.unsqueeze(0) #shape(1,3)
x.unsqueeze(1) #shape(3,1)


tensor([[1],
        [2],
        [3]])

In [ ]:
x = torch.tensor([[1, 2, 3]])

x.squeeze()   # shape (3,)


tensor([1, 2, 3])

### Broadcasting

In [31]:
A = torch.tensor([[1, 2, 3],
                  [4, 5, 6]])

b = torch.tensor([10, 20, 30])

A + b


tensor([[11, 22, 33],
        [14, 25, 36]])

### In-place vs Out-of-place Operations

In [ ]:
x = torch.tensor([1, 2, 3])
y = x + 1

print(x) # unchanged



tensor([1, 2, 3])


In [30]:
x = torch.tensor([1, 2, 3])
x.add_(1)

print(x)  


tensor([2, 3, 4])
